---
- name: Configure DB servers
  hosts: db 
  tasks:
    - name: Imports the variables file
      include_vars: paths.yml

    - name: Creates the remote directory
      file: 
        path: "{{ paths.dbpath }}"
        state: directory
        mode: 0755
      register: result 

    - name: Debugs the results 
      debug: 
        var: result 
