---
- name: Configure fileservers
  hosts: serverc
  tasks:
    - name: Imports the variables fileserver
      include_vars: paths.yml

    - name: Creates the remnote directory 
      file: 
        path: "{{ paths.fileserver }}"
        state: directory
        mode: 0755
      register: result

    - name: Debugs the results
      debug:
        var: result
