---
- name: install TomCat & start the service
  hosts: serverd

  tasks:
    - name: Install the required package
      yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: latest

    - name: Start the service
      service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"

    - name: connect to intranet web server
      uri: 
        url: http://192.168.0.120
        status_code: 200
